name: Node.js CI

on:
  push:
    branches: [master-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v2
        with:
          node-version:
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/falko-front
            git reset --hard
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm run build
            pm2 reload falko-front